name: 'Prod Deploy'
run-name: 'Deploy to production'
on: 
  push:
    branches:
      - '*'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge']
    steps:
      - name: 'Check out source code'
        uses: actions/checkout@v3
        with: 
          ref: master
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: 'Run automated tests'
        uses: cypress-io/github-action@v5
        with:
          install-command: npm ci
          start: npm run serve
          wait-on: 'http://localhost:8080'
          command: npm run cypress:run:${{ matrix.browser }}
