name: 'Prod Deploy'
run-name: 'Deploy to production'
on: 
  push:
    branches:
      - '*'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Running automated tests'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm cypress:run:chrome
