name: 'Prod Deploy'
run-name: 'Deploy to production'
on: 
  push:
    branches:
      - '*'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out source code'
        uses: actions/checkout@v3
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Start local http-server'
        run: npm run serve
      - name: 'Run automated tests'
        run: npm run cypress:run:chrome
